In [2]:
zoo_tup = ('dog', 'cat', 'wolf')
zoo_list = ['dog', 'cat', 'wolf']
    
zoo_dict = {
    'dog': 1,
    'cat': 2,
    'wolf': 3
}
type(zoo_tup)


tuple

- list 和 dict 是可变的，tuple 是不可变的

In [3]:
zoo_tup[0] = 'lion'

TypeError: 'tuple' object does not support item assignment

- 三种数据结构是异构(元素类型可以不一样)的，可嵌套的

In [5]:
new_zoo_tup = (zoo_tup, zoo_list)
print(new_zoo_tup)
print(type(new_zoo_tup[0]))
print(type(new_zoo_tup[1]))

(('dog', 'cat', 'wolf'), ['dog', 'cat', 'wolf'])
<class 'tuple'>
<class 'list'>


numpy 是高性能科学计算和数据分析的基础包

- ndarray，一个具有矢量算术运算和复杂广播能力的快速且节省空间的多维数组
- 用于对整数数组快速运算的标准数学函数
- 用于读写磁盘数据的工具以及操作内存映射文件的工具
- 线性代数，随机数生成以及傅里叶变换
- 用于集成 C,C++,Fortran 等语言编写的代码

### ndarray
一种多维数组，其是一个快速且灵活的大数据容器，且是一个同构数据容器，即其中所有元素必须是相同类型，对该数组可以直接运算

### 创建 ndarray

In [4]:
import numpy as np
data1 = [6, 5, 7, 1, 3]
arr1 = np.array(data1)
arr1

array([6, 5, 7, 1, 3])

In [5]:
data2 = [[1,2,3], [3,2,1]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3],
       [3, 2, 1]])

array 创建时是对原始对象的一分 copy 创建的，而 asarray 不是，如果修改 asarray 里的值，也会修改原数据

In [12]:
arr0 = np.zeros((2, 3))
arr2 = np.asarray(arr0)
arr2[0][0] = 100
print(arr0)
print(arr2)


[[100.   0.   0.]
 [  0.   0.   0.]]
[[100.   0.   0.]
 [  0.   0.   0.]]


ones() 创建全是 1 的数组

In [13]:
# empty函数用来创建一个没有任何值的数组，根据上一次创建的内存的值
np.empty((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.eye(4) # 对角矩阵

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 数组切片

数组索引有 `[][]`的方式访问，也有 `[,]` 的方式访问

In [10]:
arr3 = np.array([[2,1,4],[4,7,5]])
arr3

array([[2, 1, 4],
       [4, 7, 5]])

In [11]:
split1 = arr3[:2][:2]
split1

array([[2, 1, 4],
       [4, 7, 5]])

In [13]:
split1[0, 0] = 99
split1

array([[99,  1,  4],
       [ 4,  7,  5]])

切片只是原始数组的一个视图，对其进行赋值会直接影响到原始数据的值

In [14]:
arr3

array([[99,  1,  4],
       [ 4,  7,  5]])

#### 布尔型索引

In [15]:
words = np.array(list('abcdabcd'))
words

array(['a', 'b', 'c', 'd', 'a', 'b', 'c', 'd'], dtype='<U1')

In [19]:
data = np.random.randn(8,4)
data

array([[ 0.24555159, -0.3564267 ,  0.24572713,  0.99509059],
       [ 0.85066918,  0.91283672, -0.47830481,  0.02822075],
       [-2.58632514,  0.01980384,  0.4569624 ,  1.48609098],
       [ 0.07479939,  1.18169982,  0.33217491, -1.11973773],
       [-0.81632882, -0.41036484, -0.02583632,  0.25979325],
       [-0.85235171, -0.87408594, -0.0951882 , -0.34200572],
       [ 1.98133128, -0.77875892, -0.57617586,  0.59959606],
       [-1.21250364,  1.0264202 , -1.27061155,  0.60749584]])

对数组进行判断也也是矢量化的

In [17]:
words == 'a'

array([ True, False, False, False,  True, False, False, False])

In [20]:
data[words == 'a']

array([[ 0.24555159, -0.3564267 ,  0.24572713,  0.99509059],
       [-0.81632882, -0.41036484, -0.02583632,  0.25979325]])

注意：布尔数组的长度必须和索引轴的长度一致，此外还可以将布尔索引和切片混合使用

In [22]:
data[words == 'a', 2:]

array([[ 0.24572713,  0.99509059],
       [-0.02583632,  0.25979325]])

In [23]:
data[words != 'a']

array([[ 0.85066918,  0.91283672, -0.47830481,  0.02822075],
       [-2.58632514,  0.01980384,  0.4569624 ,  1.48609098],
       [ 0.07479939,  1.18169982,  0.33217491, -1.11973773],
       [-0.85235171, -0.87408594, -0.0951882 , -0.34200572],
       [ 1.98133128, -0.77875892, -0.57617586,  0.59959606],
       [-1.21250364,  1.0264202 , -1.27061155,  0.60749584]])

也可以直接根据数组的值进行条件筛选

In [24]:
data[data > 0]

array([0.24555159, 0.24572713, 0.99509059, 0.85066918, 0.91283672,
       0.02822075, 0.01980384, 0.4569624 , 1.48609098, 0.07479939,
       1.18169982, 0.33217491, 0.25979325, 1.98133128, 0.59959606,
       1.0264202 , 0.60749584])

In [26]:
data[(data > 0) & (data < 1)] # 注意这里的逻辑判断和一般的 python 语法不太一样

array([0.24555159, 0.24572713, 0.99509059, 0.85066918, 0.91283672,
       0.02822075, 0.01980384, 0.4569624 , 0.07479939, 0.33217491,
       0.25979325, 0.59959606, 0.60749584])

In [27]:
data[(data > 0) & (data < 1)] = 3
data

array([[ 3.        , -0.3564267 ,  3.        ,  3.        ],
       [ 3.        ,  3.        , -0.47830481,  3.        ],
       [-2.58632514,  3.        ,  3.        ,  1.48609098],
       [ 3.        ,  1.18169982,  3.        , -1.11973773],
       [-0.81632882, -0.41036484, -0.02583632,  3.        ],
       [-0.85235171, -0.87408594, -0.0951882 , -0.34200572],
       [ 1.98133128, -0.77875892, -0.57617586,  3.        ],
       [-1.21250364,  1.0264202 , -1.27061155,  3.        ]])

## 花式索引 Fency index
主要指使用整数数组进行索引，python 原生是没有的

In [31]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

加入我们想以某种特定顺序选取子集，只需传入一个用于指定行数顺序的整数数组或者 ndarray 即可

In [32]:
arr[[3, 5, 1, 6]]

array([[3., 3., 3., 3.],
       [5., 5., 5., 5.],
       [1., 1., 1., 1.],
       [6., 6., 6., 6.]])

In [33]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [34]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

如果想得到矩阵，可以这样操作

In [36]:
arr[[1, 5, 7, 2]][:, [0, 2, 1, 3]] # 把第 1、5、7、2行拿出来，并更换它们第2和第3列的位置

array([[ 4,  6,  5,  7],
       [20, 22, 21, 23],
       [28, 30, 29, 31],
       [ 8, 10,  9, 11]])

In [37]:
arr[np.ix_([1, 5, 7, 2], [0, 2, 1, 3])] # 上面的写法和这里的写法效果一样

array([[ 4,  6,  5,  7],
       [20, 22, 21, 23],
       [28, 30, 29, 31],
       [ 8, 10,  9, 11]])

注意：花式索引和数组切片不一样，花式索引是将数据复制到新数组中，而切片只是原始数据的一份视图，改变切片数据会改变原始数据，而改变花式索引产生的数组并不会改变原始数据

In [38]:
a = arr[np.ix_([1, 5, 7, 2], [0, 2, 1, 3])]
a

array([[ 4,  6,  5,  7],
       [20, 22, 21, 23],
       [28, 30, 29, 31],
       [ 8, 10,  9, 11]])

In [39]:
a[0][0] = 10000

In [40]:
a

array([[10000,     6,     5,     7],
       [   20,    22,    21,    23],
       [   28,    30,    29,    31],
       [    8,    10,     9,    11]])

In [41]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

## 通用函数
对数组进行元素级的运算的函数

In [45]:
data

array([[ 3.        , -0.3564267 ,  3.        ,  3.        ],
       [ 3.        ,  3.        , -0.47830481,  3.        ],
       [-2.58632514,  3.        ,  3.        ,  1.48609098],
       [ 3.        ,  1.18169982,  3.        , -1.11973773],
       [-0.81632882, -0.41036484, -0.02583632,  3.        ],
       [-0.85235171, -0.87408594, -0.0951882 , -0.34200572],
       [ 1.98133128, -0.77875892, -0.57617586,  3.        ],
       [-1.21250364,  1.0264202 , -1.27061155,  3.        ]])

In [44]:
np.exp(data) # 对每个元素进行指数函数的运算即 e的x次方，x是元素

array([[20.08553692,  0.70017379, 20.08553692, 20.08553692],
       [20.08553692, 20.08553692,  0.61983324, 20.08553692],
       [ 0.07529624, 20.08553692, 20.08553692,  4.41978467],
       [20.08553692,  3.25991077, 20.08553692,  0.32636538],
       [ 0.44205153,  0.66340817,  0.97449459, 20.08553692],
       [ 0.42641096,  0.41724323,  0.90920181,  0.71034414],
       [ 7.25239154,  0.45897528,  0.56204359, 20.08553692],
       [ 0.29745164,  2.79105651,  0.28065993, 20.08553692]])

In [46]:
np.abs(data)

array([[3.        , 0.3564267 , 3.        , 3.        ],
       [3.        , 3.        , 0.47830481, 3.        ],
       [2.58632514, 3.        , 3.        , 1.48609098],
       [3.        , 1.18169982, 3.        , 1.11973773],
       [0.81632882, 0.41036484, 0.02583632, 3.        ],
       [0.85235171, 0.87408594, 0.0951882 , 0.34200572],
       [1.98133128, 0.77875892, 0.57617586, 3.        ],
       [1.21250364, 1.0264202 , 1.27061155, 3.        ]])

In [47]:
np.square(data)

array([[9.00000000e+00, 1.27039991e-01, 9.00000000e+00, 9.00000000e+00],
       [9.00000000e+00, 9.00000000e+00, 2.28775487e-01, 9.00000000e+00],
       [6.68907772e+00, 9.00000000e+00, 9.00000000e+00, 2.20846639e+00],
       [9.00000000e+00, 1.39641447e+00, 9.00000000e+00, 1.25381258e+00],
       [6.66392750e-01, 1.68399298e-01, 6.67515206e-04, 9.00000000e+00],
       [7.26503443e-01, 7.64026222e-01, 9.06079375e-03, 1.16967914e-01],
       [3.92567365e+00, 6.06465458e-01, 3.31978625e-01, 9.00000000e+00],
       [1.47016507e+00, 1.05353843e+00, 1.61445372e+00, 9.00000000e+00]])

In [48]:
np.sqrt(np.square(data))

array([[3.        , 0.3564267 , 3.        , 3.        ],
       [3.        , 3.        , 0.47830481, 3.        ],
       [2.58632514, 3.        , 3.        , 1.48609098],
       [3.        , 1.18169982, 3.        , 1.11973773],
       [0.81632882, 0.41036484, 0.02583632, 3.        ],
       [0.85235171, 0.87408594, 0.0951882 , 0.34200572],
       [1.98133128, 0.77875892, 0.57617586, 3.        ],
       [1.21250364, 1.0264202 , 1.27061155, 3.        ]])

通用函数汇总： 一元函数

- abs, fabs 计算整数和浮点数的绝对值
- sqrt 开平方
- square 求平方
- exp 指数运算，底数为 e
- log, log2, log10, log1p 对数运算，最后一个位 log（1+x）
- sign 计算各元素的正负号
- cell 计算各元素大于等于该值得最小整数
- floor
- rint 将各个元素四舍五入
- modf 将数组的小数和整数部分以两个独立数组形式返回
- isnan 判断各个元素是否是 NaN
- isfinite, iisinf 判断无穷
- cos,cosh,sin,sinh,tan,tanh 普通和双曲型三角函数
- arccos,arcsin... 反三角

二元函数

- add
- subtract
- multiply
- divide, floor_divide 元素除法或者向下整数（舍弃余数）
- power 指数函数
- mod 取模

## 数学统计方法

求平均，和，方差等

In [49]:
data.mean()

1.0275167622993358

In [50]:
np.mean(data)

1.0275167622993358

In [53]:
data

array([[ 3.        , -0.3564267 ,  3.        ,  3.        ],
       [ 3.        ,  3.        , -0.47830481,  3.        ],
       [-2.58632514,  3.        ,  3.        ,  1.48609098],
       [ 3.        ,  1.18169982,  3.        , -1.11973773],
       [-0.81632882, -0.41036484, -0.02583632,  3.        ],
       [-0.85235171, -0.87408594, -0.0951882 , -0.34200572],
       [ 1.98133128, -0.77875892, -0.57617586,  3.        ],
       [-1.21250364,  1.0264202 , -1.27061155,  3.        ]])

In [54]:
np.mean(data, axis=0) # 计算每列平均值

array([0.68922775, 0.72356045, 0.81923541, 1.87804344])

In [55]:
np.mean(data, axis=1) # 计算每行平均值

array([ 2.16089333,  2.1304238 ,  1.22494146,  1.51549052,  0.43686751,
       -0.54090789,  0.90659912,  0.38582625])