# numpy

In [2]:
zoo_tup = ('dog', 'cat', 'wolf')
zoo_list = ['dog', 'cat', 'wolf']
    
zoo_dict = {
    'dog': 1,
    'cat': 2,
    'wolf': 3
}
type(zoo_tup)


tuple

- list 和 dict 是可变的，tuple 是不可变的

In [3]:
zoo_tup[0] = 'lion'

TypeError: 'tuple' object does not support item assignment

- 三种数据结构是异构(元素类型可以不一样)的，可嵌套的

In [ ]:
new_zoo_tup = (zoo_tup, zoo_list)
print(new_zoo_tup)
print(type(new_zoo_tup[0]))
print(type(new_zoo_tup[1]))

numpy 是高性能科学计算和数据分析的基础包

- ndarray，一个具有矢量算术运算和复杂广播能力的快速且节省空间的多维数组
- 用于对整数数组快速运算的标准数学函数
- 用于读写磁盘数据的工具以及操作内存映射文件的工具
- 线性代数，随机数生成以及傅里叶变换
- 用于集成 C,C++,Fortran 等语言编写的代码

### ndarray
一种多维数组，其是一个快速且灵活的大数据容器，且是一个同构数据容器，即其中所有元素必须是相同类型，对该数组可以直接运算

### 创建 ndarray

In [4]:
import numpy as np
data1 = [6, 5, 7, 1, 3]
arr1 = np.array(data1)
arr1

array([6, 5, 7, 1, 3])

In [5]:
data2 = [[1,2,3], [3,2,1]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3],
       [3, 2, 1]])

array 创建时是对原始对象的一分 copy 创建的，而 asarray 不是，如果修改 asarray 里的值，也会修改原数据

In [6]:
arr0 = np.zeros((2, 3))
arr2 = np.asarray(arr0)
arr2[0][0] = 100
print(arr0)
print(arr2)


[[100.   0.   0.]
 [  0.   0.   0.]]
[[100.   0.   0.]
 [  0.   0.   0.]]


ones() 创建全是 1 的数组

In [7]:
# empty函数用来创建一个没有任何值的数组，根据上一次创建的内存的值
np.empty((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.eye(4) # 对角矩阵

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 数组切片

数组索引有 `[][]`的方式访问，也有 `[,]` 的方式访问

In [9]:
arr3 = np.array([[2,1,4],[4,7,5]])
arr3

array([[2, 1, 4],
       [4, 7, 5]])

In [10]:
split1 = arr3[:2][:2]
split1

array([[2, 1, 4],
       [4, 7, 5]])

In [11]:
split1[0, 0] = 99
split1

array([[99,  1,  4],
       [ 4,  7,  5]])

切片只是原始数组的一个视图，对其进行赋值会直接影响到原始数据的值

In [12]:
arr3

array([[99,  1,  4],
       [ 4,  7,  5]])

#### 布尔型索引

In [13]:
words = np.array(list('abcdabcd'))
words

array(['a', 'b', 'c', 'd', 'a', 'b', 'c', 'd'], dtype='<U1')

In [14]:
data = np.random.randn(8,4)
data

array([[-0.15607011,  1.20020277,  0.66407412, -1.0434368 ],
       [ 0.74115718,  0.23863826,  0.41354893, -0.8840675 ],
       [ 1.67726372,  0.21187931,  0.57718186,  0.48446065],
       [-0.15002224,  1.30452207, -0.05122672, -2.86812723],
       [-0.20636819,  0.4386966 , -0.61081116, -0.04423188],
       [-0.95903048,  1.46060724, -2.06937053,  0.80675891],
       [ 0.98512045, -0.60771819, -1.33324379,  0.57753255],
       [-0.51045171,  1.3668474 , -1.24298965,  3.19088125]])

对数组进行判断也也是矢量化的

In [15]:
words == 'a'

array([ True, False, False, False,  True, False, False, False])

In [16]:
data[words == 'a']

array([[-0.15607011,  1.20020277,  0.66407412, -1.0434368 ],
       [-0.20636819,  0.4386966 , -0.61081116, -0.04423188]])

注意：布尔数组的长度必须和索引轴的长度一致，此外还可以将布尔索引和切片混合使用

In [17]:
data[words == 'a', 2:]

array([[ 0.66407412, -1.0434368 ],
       [-0.61081116, -0.04423188]])

In [18]:
data[words != 'a']

array([[ 0.74115718,  0.23863826,  0.41354893, -0.8840675 ],
       [ 1.67726372,  0.21187931,  0.57718186,  0.48446065],
       [-0.15002224,  1.30452207, -0.05122672, -2.86812723],
       [-0.95903048,  1.46060724, -2.06937053,  0.80675891],
       [ 0.98512045, -0.60771819, -1.33324379,  0.57753255],
       [-0.51045171,  1.3668474 , -1.24298965,  3.19088125]])

也可以直接根据数组的值进行条件筛选

In [19]:
data[data > 0]

array([1.20020277, 0.66407412, 0.74115718, 0.23863826, 0.41354893,
       1.67726372, 0.21187931, 0.57718186, 0.48446065, 1.30452207,
       0.4386966 , 1.46060724, 0.80675891, 0.98512045, 0.57753255,
       1.3668474 , 3.19088125])

In [20]:
data[(data > 0) & (data < 1)] # 注意这里的逻辑判断和一般的 python 语法不太一样

array([0.66407412, 0.74115718, 0.23863826, 0.41354893, 0.21187931,
       0.57718186, 0.48446065, 0.4386966 , 0.80675891, 0.98512045,
       0.57753255])

In [21]:
data[(data > 0) & (data < 1)] = 3
data

array([[-0.15607011,  1.20020277,  3.        , -1.0434368 ],
       [ 3.        ,  3.        ,  3.        , -0.8840675 ],
       [ 1.67726372,  3.        ,  3.        ,  3.        ],
       [-0.15002224,  1.30452207, -0.05122672, -2.86812723],
       [-0.20636819,  3.        , -0.61081116, -0.04423188],
       [-0.95903048,  1.46060724, -2.06937053,  3.        ],
       [ 3.        , -0.60771819, -1.33324379,  3.        ],
       [-0.51045171,  1.3668474 , -1.24298965,  3.19088125]])

## 花式索引 Fency index
主要指使用整数数组进行索引，python 原生是没有的

In [22]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

加入我们想以某种特定顺序选取子集，只需传入一个用于指定行数顺序的整数数组或者 ndarray 即可

In [23]:
arr[[3, 5, 1, 6]]

array([[3., 3., 3., 3.],
       [5., 5., 5., 5.],
       [1., 1., 1., 1.],
       [6., 6., 6., 6.]])

In [24]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [25]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

如果想得到矩阵，可以这样操作

In [26]:
arr[[1, 5, 7, 2]][:, [0, 2, 1, 3]] # 把第 1、5、7、2行拿出来，并更换它们第2和第3列的位置

array([[ 4,  6,  5,  7],
       [20, 22, 21, 23],
       [28, 30, 29, 31],
       [ 8, 10,  9, 11]])

In [27]:
arr[np.ix_([1, 5, 7, 2], [0, 2, 1, 3])] # 上面的写法和这里的写法效果一样

array([[ 4,  6,  5,  7],
       [20, 22, 21, 23],
       [28, 30, 29, 31],
       [ 8, 10,  9, 11]])

注意：花式索引和数组切片不一样，花式索引是将数据复制到新数组中，而切片只是原始数据的一份视图，改变切片数据会改变原始数据，而改变花式索引产生的数组并不会改变原始数据

In [28]:
a = arr[np.ix_([1, 5, 7, 2], [0, 2, 1, 3])]
a

array([[ 4,  6,  5,  7],
       [20, 22, 21, 23],
       [28, 30, 29, 31],
       [ 8, 10,  9, 11]])

In [29]:
a[0][0] = 10000

In [30]:
a

array([[10000,     6,     5,     7],
       [   20,    22,    21,    23],
       [   28,    30,    29,    31],
       [    8,    10,     9,    11]])

In [31]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

## 通用函数
对数组进行元素级的运算的函数

In [32]:
data

array([[-0.15607011,  1.20020277,  3.        , -1.0434368 ],
       [ 3.        ,  3.        ,  3.        , -0.8840675 ],
       [ 1.67726372,  3.        ,  3.        ,  3.        ],
       [-0.15002224,  1.30452207, -0.05122672, -2.86812723],
       [-0.20636819,  3.        , -0.61081116, -0.04423188],
       [-0.95903048,  1.46060724, -2.06937053,  3.        ],
       [ 3.        , -0.60771819, -1.33324379,  3.        ],
       [-0.51045171,  1.3668474 , -1.24298965,  3.19088125]])

In [33]:
np.exp(data) # 对每个元素进行指数函数的运算即 e的x次方，x是元素

array([[ 0.85549921,  3.32079021, 20.08553692,  0.35224202],
       [20.08553692, 20.08553692, 20.08553692,  0.41309921],
       [ 5.35089436, 20.08553692, 20.08553692, 20.08553692],
       [ 0.86068883,  3.68592704,  0.95006325,  0.05680521],
       [ 0.81353349, 20.08553692,  0.5429103 ,  0.95673209],
       [ 0.38326429,  4.30857509,  0.12626524, 20.08553692],
       [20.08553692,  0.54459211,  0.26362074, 20.08553692],
       [ 0.60022439,  3.92296363,  0.28852035, 24.30984102]])

In [34]:
np.abs(data)

array([[0.15607011, 1.20020277, 3.        , 1.0434368 ],
       [3.        , 3.        , 3.        , 0.8840675 ],
       [1.67726372, 3.        , 3.        , 3.        ],
       [0.15002224, 1.30452207, 0.05122672, 2.86812723],
       [0.20636819, 3.        , 0.61081116, 0.04423188],
       [0.95903048, 1.46060724, 2.06937053, 3.        ],
       [3.        , 0.60771819, 1.33324379, 3.        ],
       [0.51045171, 1.3668474 , 1.24298965, 3.19088125]])

In [35]:
np.square(data)

array([[2.43578806e-02, 1.44048669e+00, 9.00000000e+00, 1.08876035e+00],
       [9.00000000e+00, 9.00000000e+00, 9.00000000e+00, 7.81575340e-01],
       [2.81321358e+00, 9.00000000e+00, 9.00000000e+00, 9.00000000e+00],
       [2.25066723e-02, 1.70177782e+00, 2.62417647e-03, 8.22615379e+00],
       [4.25878279e-02, 9.00000000e+00, 3.73090277e-01, 1.95645885e-03],
       [9.19739455e-01, 2.13337352e+00, 4.28229440e+00, 9.00000000e+00],
       [9.00000000e+00, 3.69321398e-01, 1.77753900e+00, 9.00000000e+00],
       [2.60560945e-01, 1.86827181e+00, 1.54502327e+00, 1.01817231e+01]])

In [36]:
np.sqrt(np.square(data))

array([[0.15607011, 1.20020277, 3.        , 1.0434368 ],
       [3.        , 3.        , 3.        , 0.8840675 ],
       [1.67726372, 3.        , 3.        , 3.        ],
       [0.15002224, 1.30452207, 0.05122672, 2.86812723],
       [0.20636819, 3.        , 0.61081116, 0.04423188],
       [0.95903048, 1.46060724, 2.06937053, 3.        ],
       [3.        , 0.60771819, 1.33324379, 3.        ],
       [0.51045171, 1.3668474 , 1.24298965, 3.19088125]])

通用函数汇总： 一元函数

- abs, fabs 计算整数和浮点数的绝对值
- sqrt 开平方
- square 求平方
- exp 指数运算，底数为 e
- log, log2, log10, log1p 对数运算，最后一个位 log（1+x）
- sign 计算各元素的正负号
- cell 计算各元素大于等于该值得最小整数
- floor
- rint 将各个元素四舍五入
- modf 将数组的小数和整数部分以两个独立数组形式返回
- isnan 判断各个元素是否是 NaN
- isfinite, iisinf 判断无穷
- cos,cosh,sin,sinh,tan,tanh 普通和双曲型三角函数
- arccos,arcsin... 反三角

二元函数

- add
- subtract
- multiply
- divide, floor_divide 元素除法或者向下整数（舍弃余数）
- power 指数函数
- mod 取模

## 数学统计方法

求平均，和，方差等

In [37]:
data.mean()

0.9519736964570076

In [38]:
np.mean(data)

0.9519736964570076

In [39]:
data

array([[-0.15607011,  1.20020277,  3.        , -1.0434368 ],
       [ 3.        ,  3.        ,  3.        , -0.8840675 ],
       [ 1.67726372,  3.        ,  3.        ,  3.        ],
       [-0.15002224,  1.30452207, -0.05122672, -2.86812723],
       [-0.20636819,  3.        , -0.61081116, -0.04423188],
       [-0.95903048,  1.46060724, -2.06937053,  3.        ],
       [ 3.        , -0.60771819, -1.33324379,  3.        ],
       [-0.51045171,  1.3668474 , -1.24298965,  3.19088125]])

In [40]:
np.mean(data, axis=0) # 计算每列平均值

array([0.71191512, 1.71555766, 0.46154477, 0.91887723])

In [41]:
np.mean(data, axis=1) # 计算每行平均值

array([ 0.75017397,  2.02898313,  2.66931593, -0.44121353,  0.53464719,
        0.35805156,  1.01475951,  0.70107182])

In [42]:
np.cumsum([1,2,3])

array([1, 3, 6], dtype=int32)

In [43]:
np.cumprod([1,2,3])

array([1, 2, 6], dtype=int32)

基本数学统计方法

- sum 求和
- mean 平均值
- std，var 标准差和方差
- min，max
- argmin，argmax 最小值和最大值的索引
- cumsum 累计和，从前到后一个个加起来
- cumprod 累计积，从前到后一个个乘起来

### 线性代数

In [44]:
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[6,20], [-1,3],[9,8]])

In [45]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
y

array([[ 6, 20],
       [-1,  3],
       [ 9,  8]])

In [47]:
x.dot(y) # 等价于 np.dot(x, y)

array([[ 31,  50],
       [ 73, 143]])

numpy.linalg 中有一组标准的线性代数运算函数

In [48]:
X = np.random.randn(5, 5)
X

array([[ 0.34286719,  0.94509069, -1.59330486, -0.16558256, -1.28482122],
       [ 1.17165349,  0.18725789, -1.40200646,  2.00060888,  0.34517841],
       [-0.20480191, -0.82593823,  0.25775354, -1.18646722, -1.74601665],
       [-1.71736629,  0.00938829,  0.67251057,  0.26558373, -2.33013256],
       [-0.1939038 ,  0.49655313, -1.40096685,  0.11796605,  0.23951553]])

In [49]:
inv_X = np.linalg.inv(X) # 逆矩阵
inv_X

array([[ 0.4136395 ,  0.14787852,  0.04459261, -0.31800136, -0.76286305],
       [ 0.75854742, -0.37782788, -0.79037569,  0.05602295, -0.60310225],
       [ 0.15088214, -0.14214266, -0.32446217,  0.05927496, -0.77438274],
       [-0.15980906,  0.36790638, -0.15410816,  0.24826719, -0.09560696],
       [-0.27647437, -0.10960374, -0.14725985, -0.1491548 ,  0.32542395]])

In [50]:
X.T # 转置矩阵

array([[ 0.34286719,  1.17165349, -0.20480191, -1.71736629, -0.1939038 ],
       [ 0.94509069,  0.18725789, -0.82593823,  0.00938829,  0.49655313],
       [-1.59330486, -1.40200646,  0.25775354,  0.67251057, -1.40096685],
       [-0.16558256,  2.00060888, -1.18646722,  0.26558373,  0.11796605],
       [-1.28482122,  0.34517841, -1.74601665, -2.33013256,  0.23951553]])

线性代数函数

- diag 以一位数组的形式返回方阵的对角线元素，或者将一位数组转化为方阵
- dot 矩阵乘法
- trace 计算对角线元素的和
- det 计算矩阵行列式
- elg 计算方阵的本征值和本征向量
- inv 计算方阵的逆
- pinv 计算矩阵的 Moore-Penrose 伪逆
- qr 计算 QR 分解
- svd 计算奇异值分解
- solve 解线性方程组 Ax= b，其中 A 是一个方阵
- lstsq 计算 Ax= b 的最小二乘解

随机数生成
numpy.random 高效生成多种概率分布的样本值函数，而且性能比原生的好

In [51]:
np.random.normal(size=(4, 4))

array([[ 0.86879507, -0.37489122, -0.00190121, -0.05525285],
       [-0.82479739,  0.71955731, -0.11653009,  0.83965204],
       [-0.74218963,  0.36677638,  0.81524276,  1.28258536],
       [ 0.49629701, -0.40681978,  0.06562846,  0.82430216]])

In [52]:
import random
N = 1000000

In [53]:
%timeit samples = [random.normalvariate(0, 1) for _ in range(N)]

1.73 s ± 235 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [54]:
%timeit np.random.normal(size=N)

51.4 ms ± 1.63 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


- seed 确定随机数生成器的种子
- permutation 返回一个序列的随机排列
- shuffle 对一个序列随机排序
- randint 从非定的上下限范围随机选取整数
- randn 产生正态分布熟知
- binomial 产生二项分布数值
- normal 产生高斯分布
- beta 产生 beta 分布